Translate Finding Users guide to spanish (es-ES).
coopdevs/opensource.guide pull request #31
Opened 2018-02-02 19:42 UTC by ygneo

2018-02-03 18:36 UTC, sauloperez requested changes

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +description: Facilita el crecimiento de tu poryecto poniéndolo ne las manos de usuarios felices.
s/poryecto/proyecto, s/ne/en

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +Antes de comenzar con el trabajo de promocionar tu proyecto, deberías ser capaz de explicar qué hace, y por qué es importante.
s/de promocionar/de promoción?

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +Para entrar con más profundidad en en el tema del envío de mensajes efectivos, échale un ojo [a este ejercicio de Mozilla](https://mozillascience.github.io/working-open-workshop/personas_pathways/).
sobra un "en"

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +Participar en en la comunidad online es una buena manera de difundir la palabra rápidamente. Usando canales onnline tienes el potenciar de llegar a una audiencia amplia.
sobra un "en" y s/onnline/online

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +* **Encuentra a gente que sufra el problema que tu proyecto resuelve** Busca en foros relacionados a gente que pueda caer en tu audiencia objetivo. Responde a su pregunta con tacto, cuando sea apropi
"audiencia objetiva" parece traducción de "target audience" pero suena muy mal en castellano. "Buscar en foros relacionados a gente que pueda ser tu audiencia"?

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +Si alguien presta atención o responde a tu aproximación inicial, ¡no te desanimes! La mayoría de los lanzamientos de proyectos son procesos iterativos que pueden tomar meses o años. Si no obtienes un
Esta primera frase, no deberia ser una negación. Si no, "¡no te desanimes!" no tiene sentido, creo.

2018-02-03 18:36 UTC, sauloperez commented on _articles/es-ES/finding-users.md
> +Mientras escribes tu charla, enfócate en lo que tu audiencia encuentra interesante y sácale valor. Mantén tu lenguaje amigable y accesible. Sonrie, respira y pástelo bien.
s/pástelo/pásatelo

2018-02-03 19:09 UTC, ygneo commented
Aplicados los cambios solicitados. :)

2018-02-04 18:23 UTC, sauloperez approved these changes

2018-02-04 18:39 UTC, merged